name: 'Close issue when opened'
description: 'Closes a newly opened issue, tags it and puts it in the proper column in Smackore project board.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  ISSUE_URL:
    description: 'Issue URL'
    required: true
  ISSUE_NUMBER:
    description: 'Issue number'
    required: true
  REPOSITORY:
    description: 'Repository'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '26.1'
        elixir-version: '1.15.6'
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Create ticket and close issue
      run: |
        export PROJECT_NUMBER=19
        export PROJECT_ID=PVT_kwDOAYE_z84AWEIB
        export STATUS_FIELD_ID=PVTSSF_lADOAYE_z84AWEIBzgOGd1k
        export TARGET_COLUMN_ID=fa223107
        export CORE_URL=https://github.com/membraneframework/membrane_core
        export ISSUE_CLOSE_COMMENT="Issues related to $REPOSITORY are stored in [membrane_core]($CORE_URL), so we close this issue here and we encourage you to open it [there]($CORE_URL)."

        gh issue edit $ISSUE_URL --add-project "Smackore"
        sleep 10        

        export TICKET_ID=$(gh project item-list $PROJECT_NUMBER --owner membraneframework --format json --limit 10000000 | elixir get_ticket_id.exs "$ISSUE_URL" | awk '/TICKET_ID/{print $2}')
        gh issue close $ISSUE_URL --comment "$ISSUE_CLOSE_COMMENT" --reason "not planned"
        sleep 10

        gh project item-edit --id $TICKET_ID --field-id $STATUS_FIELD_ID --project-id $PROJECT_ID --single-select-option-id $TARGET_COLUMN_ID
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ISSUE_URL: ${{ inputs.ISSUE_URL }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
      shell: bash
