name: 'Add PR to Smackore board, if author is from community'
description: 'Adds PR to "New issues by community" column in Smackore project board, if PR author is from outside Membrane Team.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  AUTHOR_LOGIN:
    description: 'PR author login'
    required: true
  PR_URL:
    description: 'PR URL'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout membrane_core code
      uses: actions/checkout@v3
      with:
        repository: membraneframework/membrane_core
    - name: Maybe add PR to board and set ticket status
      run: | 
          export PROJECT_NUMBER=19
          export PROJECT_ID=PVT_kwDOAYE_z84AWEIB
          export STATUS_FIELD_ID=PVTSSF_lADOAYE_z84AWEIBzgOGd1k
          export TARGET_COLUMN_ID=e6b1ee10
          
          export AUTHOR_ORIGIN=$(curl --request GET --url "https://api.github.com/orgs/membraneframework/members" --header "Authorization: Bearer $GH_TOKEN" -s | python scripts/python/get_author_origin.py $AUTHOR_LOGIN)

          if [ "$AUTHOR_ORIGIN" == "COMMUNITY" ]
          then
            gh pr edit "$PR_URL" --add-project Smackore
            sleep 10

            export TICKET_ID=$(gh project item-list $PROJECT_NUMBER --owner membraneframework --format json --limit 10000000 | python scripts/python/get_ticket_id.py "$PR_URL")
            gh project item-edit --id $TICKET_ID --field-id $STATUS_FIELD_ID --project-id $PROJECT_ID --single-select-option-id $TARGET_COLUMN_ID
          fi

      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        AUTHOR_LOGIN: ${{ inputs.AUTHOR_LOGIN }}
        PR_URL: ${{ inputs.PR_URL }}
      shell: bash
