name: 'Create label'
description: 'Creates a label closed-by-membrane-bot, if it does not exist.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        gh label create closed-by-membrane-bot --description "Automatically closed by Membrane bot" --color EB3467 || true
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      shell: bash
