# Packages in the membrane ecosystem and their categories
[
  {:section, "General"},
  "membrane_sdk",
  "membrane_core",
  "membrane_rtc_engine",
  "kino_membrane",
  "docker_membrane",
  "membrane_demo",
  "membrane_tutorials",
  "boombox",
  {:section, "Plugins"},
  {:subsection, "General purpose"},
  "membrane_file_plugin",
  "membrane_hackney_plugin",
  "membrane_scissors_plugin",
  "membrane_tee_plugin",
  "membrane_funnel_plugin",
  "membrane_realtimer_plugin",
  "membrane_stream_plugin",
  "membrane_fake_plugin",
  "membrane_pcap_plugin",
  "membrane_transcoder_plugin",
  "membrane_generator_plugin",
  "kim-company/membrane_live_framerate_converter_plugin",
  "membrane_template_plugin",
  {:subsection, "Streaming protocols"},
  "membrane_webrtc_plugin",
  "membrane_rtmp_plugin",
  "membrane_http_adaptive_stream_plugin",
  "membrane_srt_plugin",
  "membrane_udp_plugin",
  "membrane_tcp_plugin",
  "membrane_rtp_plugin",
  "membrane_rtp_h264_plugin",
  "membrane_rtp_aac_plugin",
  "membrane_rtp_vp8_plugin",
  "membrane_rtp_vp9_plugin",
  "membrane_rtp_mpegaudio_plugin",
  "membrane_rtp_opus_plugin",
  "membrane_rtp_g711_plugin",
  "gBillal/membrane_rtsp_plugin",
  "kim-company/membrane_mpeg_ts_plugin",
  "kim-company/membrane_hls_plugin",
  {:subsection, "Containers"},
  "membrane_mp4_plugin",
  "membrane_matroska_plugin",
  "membrane_flv_plugin",
  "membrane_ivf_plugin",
  "membrane_ogg_plugin",
  {:subsection, "Audio codecs"},
  "membrane_aac_plugin",
  "membrane_aac_fdk_plugin",
  "membrane_flac_plugin",
  "membrane_mp3_lame_plugin",
  "membrane_mp3_mad_plugin",
  "membrane_opus_plugin",
  "membrane_wav_plugin",
  "membrane_g711_plugin",
  "membrane_g711_ffmpeg_plugin",
  {:subsection, "Video codecs"},
  "membrane_h26x_plugin",
  "membrane_h264_ffmpeg_plugin",
  "membrane_vpx_plugin",
  "membrane_abr_transcoder_plugin",
  "gBillal/membrane_h265_ffmpeg_plugin",
  "binarynoggin/elixir-turbojpeg",
  "kim-company/membrane_subtitle_mixer_plugin",
  {:subsection, "Raw audio"},
  "membrane_raw_audio_parser_plugin",
  "membrane_portaudio_plugin",
  "membrane_audio_mix_plugin",
  "membrane_audio_filler_plugin",
  "membrane_ffmpeg_swresample_plugin",
  "membrane_audiometer_plugin",
  {:subsection, "Raw video"},
  "membrane_raw_video_parser_plugin",
  "membrane_video_merger_plugin",
  "membrane_smelter_plugin",
  "membrane_camera_capture_plugin",
  "membrane_rpicam_plugin",
  "membrane_framerate_converter_plugin",
  "membrane_sdl_plugin",
  "membrane_overlay_plugin",
  "membrane_ffmpeg_swscale_plugin",
  "membrane_ffmpeg_video_filter_plugin",
  "membrane_yolo_plugin",
  "kim-company/membrane_video_mixer_plugin",
  {:subsection, "External APIs"},
  "membrane_aws_plugin",
  "membrane_agora_plugin",
  "membrane_webrtc_live",
  "membrane_element_gcloud_speech_to_text",
  "membrane_element_ibm_speech_to_text",
  "YuzuTen/membrane_s3_plugin",
  "lawik/membrane_transcription",
  {:section, "Formats"},
  "membrane_rtp_format",
  "membrane_cmaf_format",
  "membrane_matroska_format",
  "membrane_mp4_format",
  "membrane_raw_audio_format",
  "membrane_raw_video_format",
  "membrane_aac_format",
  "membrane_opus_format",
  "membrane_flac_format",
  "membrane_mpegaudio_format",
  "membrane_h264_format",
  "membrane_vp8_format",
  "membrane_vp9_format",
  "membrane_g711_format",
  "gBillal/membrane_h265_format",
  {:section, "Standalone media libs"},
  "elixir-webrtc/ex_webrtc",
  "ex_sdp",
  "ex_libnice",
  "ex_libsrtp",
  "ex_m3u8",
  "ex_hls",
  "ex_libsrt",
  "membrane_rtsp",
  "membrane_ffmpeg_generator",
  {:section, "Utils"},
  "unifex",
  "bundlex",
  "beamchmark",
  "bunch",
  "bunch_native",
  "shmex",
  "membrane_timestamp_queue",
  "membrane_common_c",
  "membrane_telemetry_metrics",
  "membrane_opentelemetry",
  "membrane_precompiled_dependency_provider"
]
